eadnoth@ordi-eadnoth:~/DataEngineerTools$ sudo docker build -t image_drio  .
Sending build context to Docker daemon  150.9MB
Step 1/6 : FROM python:3.8
3.8: Pulling from library/python
647acf3d48c2: Pull complete 
b02967ef0034: Pull complete 
e1ad2231829e: Pull complete 
5576ce26bf1d: Pull complete 
a66b7f31b095: Pull complete 
05189b5b2762: Pull complete 
3b0f50bca553: Pull complete 
75eb55df9bc7: Pull complete 
1f2ae3b45e17: Pull complete 
Digest: sha256:68bddbf6e88c9c88d3238e13f02edf1884fc349a0964fad4b3d44f2425791ac7
Status: Downloaded newer image for python:3.8
 ---> 67ec76d9f73b
Step 2/6 : RUN mkdir /home/dev/ && mkdir /home/dev/code/
 ---> Running in 4087ade5dd12
Removing intermediate container 4087ade5dd12
 ---> 7065d1360384
Step 3/6 : WORKDIR /home/dev/code/
 ---> Running in 03c7c599008a
Removing intermediate container 03c7c599008a
 ---> d0d170b0af27
Step 4/6 : COPY . .
 ---> 5712e6ecbce7
Step 5/6 : RUN  pip install --upgrade pip &&  pip install pipenv && pipenv install --skip-lock
 ---> Running in 201639ecd247
Requirement already satisfied: pip in /usr/local/lib/python3.8/site-packages (21.2.4)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-21.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting pipenv
  Downloading pipenv-2021.11.15-py2.py3-none-any.whl (3.6 MB)
Requirement already satisfied: pip>=18.0 in /usr/local/lib/python3.8/site-packages (from pipenv) (21.3.1)
Collecting virtualenv-clone>=0.2.5
  Downloading virtualenv_clone-0.5.7-py3-none-any.whl (6.6 kB)
Requirement already satisfied: setuptools>=36.2.1 in /usr/local/lib/python3.8/site-packages (from pipenv) (57.5.0)
Collecting virtualenv
  Downloading virtualenv-20.10.0-py2.py3-none-any.whl (5.6 MB)
Collecting certifi
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting six<2,>=1.9.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting filelock<4,>=3.2
  Downloading filelock-3.4.0-py3-none-any.whl (9.8 kB)
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.3-py2.py3-none-any.whl (496 kB)
Collecting backports.entry-points-selectable>=1.0.4
  Downloading backports.entry_points_selectable-1.1.1-py2.py3-none-any.whl (6.2 kB)
Collecting platformdirs<3,>=2
  Downloading platformdirs-2.4.0-py3-none-any.whl (14 kB)
Installing collected packages: six, platformdirs, filelock, distlib, backports.entry-points-selectable, virtualenv-clone, virtualenv, certifi, pipenv
Successfully installed backports.entry-points-selectable-1.1.1 certifi-2021.10.8 distlib-0.3.3 filelock-3.4.0 pipenv-2021.11.15 platformdirs-2.4.0 six-1.16.0 virtualenv-20.10.0 virtualenv-clone-0.5.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Creating a virtualenv for this project...
Pipfile: /home/dev/code/Pipfile
Using /usr/local/bin/python3.8 (3.8.12) to create virtualenv...
⠇ Creating virtual environment...created virtual environment CPython3.8.12.final.0-64 in 516ms
  creator CPython3Posix(dest=/root/.local/share/virtualenvs/code-AFz48Hjb, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==21.3.1, setuptools==58.3.0, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /root/.local/share/virtualenvs/code-AFz48Hjb
Installing dependencies from Pipfile...
An error occurred while installing jupyter! Will try again.
An error occurred while installing selenium! Will try again.
An error occurred while installing cryptography==3.2.1! Will try again.
Installing initially failed dependencies...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Removing intermediate container 201639ecd247
 ---> c1267caf5146
Step 6/6 : CMD ["pipenv", "run", "jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
 ---> Running in d0dfd9e6d519
Removing intermediate container d0dfd9e6d519
 ---> 8b5c52b24dac
Successfully built 8b5c52b24dac
Successfully tagged image_drio:latest
